---
galaxy_info:
  role_name: sshd_lockdown
  author: rafal
  description: Hardening SSH — key-only, no-root, nowoczesne crypto, banner (Ubuntu)
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies: []
