---
- name: Converge
  hosts: all
  become: true
  vars:
    swap_enable: false   # kontener nie pozwala na swapon; testujemy plik + fstab
    swap_size_mb: 64     # mały plik dla szybkiego CI
  roles:
    - role: swap
